# Tasks for borgbackup - Debian-specific distributions
---
- name: Install borgbackup (Debian distributions)
  apt:
    name:
      - borgbackup
    state: latest
    update_cache: true
  when: state == 'present'

- name: Remove borgbackup (Debian distributions)
  apt:
    name:
      - borgbackup
    state: absent
  when: state == 'absent'