---
- name: Import Debian tasks
  import_tasks: debian.yaml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Remove cron job for backups
  cron:
    state: absent
    name: "borgbackup"
    job: "{{ borgbackup_config_dir }}/backup-script.sh"

- name: Remove borgbackup directories
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - "{{ borgbackup_config_dir }}"
    - "{{ borgbackup_log_dir }}"
    - "{{ borgbackup_repo }}"


- name: remove cron job for directory sync
  ansible.builtin.cron:
    backup: true
    name: "sync backup to nas"
    state: absent

- name: remove mountpoint for nas
  ansible.builtin.file:
    path: "{{ nas_backup_mountpoint }}"
    state: absent

- name: remove nas mount directive
  ansible.posix.mount:
    backup: true
    path: "{{ nas_backup_mountpoint }}"
    src: "files.ldf.edwinsummers.net:/mnt/generalpool/linux_backups/{{ inventory_hostname }}"
    state: absent
